<?php
namespace Geekwright\Po\Exceptions;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-18 at 00:42:43.
 */
class FileNotWritableExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FileNotWritableException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FileNotWritableException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testException()
    {
        $this->setExpectedException('Geekwright\Po\Exceptions\FileNotWritableException');
        throw $this->object;
    }
}
