<?php
namespace Geekwright\Po\Exceptions;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-18 at 00:41:53.
 */
class UnrecognizedInputExceptionTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var UnrecognizedInputException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UnrecognizedInputException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testContracts()
    {
        $this->assertInstanceOf('\Geekwright\Po\Exceptions\UnrecognizedInputException', $this->object);
        $this->assertInstanceOf('\UnexpectedValueException', $this->object);
    }

    public function testException()
    {
        $this->expectException('\Geekwright\Po\Exceptions\UnrecognizedInputException');
        throw $this->object;
    }
}
