<?php
namespace Geekwright\Po;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-18 at 00:36:56.
 */
class PoHeaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PoHeader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PoHeader;
        $this->object->buildDefaultHeader();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geekwright\Po\PoHeader::getHeader
     * @covers Geekwright\Po\PoHeader::setHeader
     */
    public function testGetSetHeader()
    {
        $value = 'nplurals=1; plural=0;';
        $this->object->setHeader('plural-forms', $value);
        $actual = $this->object->getHeader('Plural-Forms');
        $this->assertEquals($value, $actual);
    }

    /**
     * @covers Geekwright\Po\PoHeader::setCreateDate
     */
    public function testSetCreateDate()
    {
        $time = time();
        $expected = gmdate('Y-m-d H:iO', $time);
        $this->object->setCreateDate($time);
        $actual = $this->object->getHeader('POT-Creation-Date');
        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Geekwright\Po\PoHeader::setRevisionDate
     */
    public function testSetRevisionDate()
    {
        $time = time();
        $expected = gmdate('Y-m-d H:iO', $time);
        $this->object->setRevisionDate($time);
        $actual = $this->object->getHeader('PO-Revision-Date');
        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Geekwright\Po\PoHeader::buildDefaultHeader
     */
    public function testBuildDefaultHeader()
    {
        $header = new PoHeader;
        $header->buildDefaultHeader();
        $actual = $header->getHeader('Content-Type');
        $expected = 'text/plain; charset=UTF-8';
        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Geekwright\Po\PoHeader::dumpEntry
     */
    public function testDumpEntry()
    {
        $output = $this->object->dumpEntry();
        $actual = substr($output, -2);
        $expected = "\n\n";
        $this->assertEquals($expected, $actual);
        $actual = substr($output, 0, 1);
        $expected = "#";
        $this->assertEquals($expected, $actual);
        $this->assertTrue(false !== strpos($output, 'Content-Type'));
        $this->assertTrue(false !== strpos($output, 'PO-Revision-Date'));
    }
}
