<?php
namespace Geekwright\Po;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-18 at 00:36:56.
 */
class PoHeaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PoHeader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PoHeader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geekwright\Po\PoHeader::getHeader
     * @todo   Implement testGetHeader().
     */
    public function testGetHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoHeader::setHeader
     * @todo   Implement testSetHeader().
     */
    public function testSetHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoHeader::setCreateDate
     * @todo   Implement testSetCreateDate().
     */
    public function testSetCreateDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoHeader::setRevisionDate
     * @todo   Implement testSetRevisionDate().
     */
    public function testSetRevisionDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoHeader::buildDefaultHeader
     * @todo   Implement testBuildDefaultHeader().
     */
    public function testBuildDefaultHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoHeader::dumpEntry
     * @todo   Implement testDumpEntry().
     */
    public function testDumpEntry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
