<?php
namespace Geekwright\Po;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-18 at 00:37:40.
 */
class PoInitPHPTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PoInitPHP
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PoInitPHP;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geekwright\Po\PoInitPHP::setPoFile
     * @todo   Implement testSetPoFile().
     */
    public function testSetPoFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitPHP::setGettextTags
     * @todo   Implement testSetGettextTags().
     */
    public function testSetGettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitPHP::addGettextTags
     * @todo   Implement testAddGettextTags().
     */
    public function testAddGettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitPHP::setNgettextTags
     * @todo   Implement testSetNgettextTags().
     */
    public function testSetNgettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitPHP::addNgettextTags
     * @todo   Implement testAddNgettextTags().
     */
    public function testAddNgettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitPHP::setPgettextTags
     * @todo   Implement testSetPgettextTags().
     */
    public function testSetPgettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitPHP::addPgettextTags
     * @todo   Implement testAddPgettextTags().
     */
    public function testAddPgettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitPHP::msginitFile
     * @todo   Implement testMsginitFile().
     */
    public function testMsginitFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitPHP::msginitString
     * @todo   Implement testMsginitString().
     */
    public function testMsginitString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
