<?php
namespace Geekwright\Po;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-18 at 21:12:34.
 */
class PoInitSmartyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PoInitSmarty
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if (!class_exists('\Smarty')) {
            $this->markTestSkipped(
              'Smarty is not available.'
            );
        }
        $smarty = new \Smarty;
        $this->object = new PoInitSmarty($smarty, new PoFile);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::setPoFile
     * @todo   Implement testSetPoFile().
     */
    public function testSetPoFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::setMsgctxtArgNames
     * @todo   Implement testSetMsgctxtArgNames().
     */
    public function testSetMsgctxtArgNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::addMsgctxtArgNames
     * @todo   Implement testAddMsgctxtArgNames().
     */
    public function testAddMsgctxtArgNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::setMsgidArgNames
     * @todo   Implement testSetMsgidArgNames().
     */
    public function testSetMsgidArgNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::addMsgidArgNames
     * @todo   Implement testAddMsgidArgNames().
     */
    public function testAddMsgidArgNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::setMsgidPluralArgNames
     * @todo   Implement testSetMsgidPluralArgNames().
     */
    public function testSetMsgidPluralArgNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::addMsgidPluralArgNames
     * @todo   Implement testAddMsgidPluralArgNames().
     */
    public function testAddMsgidPluralArgNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::setGettextTags
     * @todo   Implement testSetGettextTags().
     */
    public function testSetGettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::addGettextTags
     * @todo   Implement testAddGettextTags().
     */
    public function testAddGettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::setNgettextTags
     * @todo   Implement testSetNgettextTags().
     */
    public function testSetNgettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::addNgettextTags
     * @todo   Implement testAddNgettextTags().
     */
    public function testAddNgettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::setPgettextTags
     * @todo   Implement testSetPgettextTags().
     */
    public function testSetPgettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::addPgettextTags
     * @todo   Implement testAddPgettextTags().
     */
    public function testAddPgettextTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::msginitFile
     * @todo   Implement testMsginitFile().
     */
    public function testMsginitFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Geekwright\Po\PoInitSmarty::msginitString
     * @todo   Implement testMsginitString().
     */
    public function testMsginitString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
