<?php
namespace Geekwright\Po;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-19 at 20:10:05.
 */
class PoInitAbstractTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PoInitAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new PoInitAbstract;
        $this->object = $this->getMockForAbstractClass('Geekwright\Po\PoInitAbstract');
        $this->object->expects($this->any())
             ->method('msginitString')
             ->will($this->returnValue(new PoFile));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geekwright\Po\PoInitAbstract::getPoFile
     * @covers Geekwright\Po\PoInitAbstract::setPoFile
     */
    public function testGetSetPoFile()
    {
        $pofile = new PoFile();
        $this->object->setPoFile($pofile);
        $actual = $this->object->getPoFile();
        $this->assertSame($pofile, $actual);
    }

    /**
     * @covers Geekwright\Po\PoInitAbstract::addGettextTags
     * @covers Geekwright\Po\PoInitAbstract::getGettextTags
     * @covers Geekwright\Po\PoInitAbstract::setGettextTags
     */
    public function testAddGetSetGettextTags()
    {
        $value = array();
        $this->object->setGettextTags($value);
        $actual = $this->object->getGettextTags();
        $this->assertEquals($value, $actual);

        $tag1 = 'tag1';
        $tag2 = 'tag2';
        $value = array($tag1, $tag2);
        $this->object->addGettextTags($tag1);
        $this->object->addGettextTags($tag2);
        $actual = $this->object->getGettextTags();
        $this->assertEquals($value, $actual);
    }

    /**
     * @covers Geekwright\Po\PoInitAbstract::addNgettextTags
     * @covers Geekwright\Po\PoInitAbstract::getNgettextTags
     * @covers Geekwright\Po\PoInitAbstract::setNgettextTags
     */
    public function testAddGetSetNgettextTags()
    {
        $value = array();
        $this->object->setNgettextTags($value);
        $actual = $this->object->getNgettextTags();
        $this->assertEquals($value, $actual);

        $tag1 = 'tag1';
        $tag2 = 'tag2';
        $value = array($tag1, $tag2);
        $this->object->addNgettextTags($tag1);
        $this->object->addNgettextTags($tag2);
        $actual = $this->object->getNgettextTags();
        $this->assertEquals($value, $actual);
    }

    /**
     * @covers Geekwright\Po\PoInitAbstract::addPgettextTags
     * @covers Geekwright\Po\PoInitAbstract::getPgettextTags
     * @covers Geekwright\Po\PoInitAbstract::setPgettextTags
     */
    public function testAddGetSetPgettextTags()
    {
        $value = array();
        $this->object->setPgettextTags($value);
        $actual = $this->object->getPgettextTags();
        $this->assertEquals($value, $actual);

        $tag1 = 'tag1';
        $tag2 = 'tag2';
        $value = array($tag1, $tag2);
        $this->object->addPgettextTags($tag1);
        $this->object->addPgettextTags($tag2);
        $actual = $this->object->getPgettextTags();
        $this->assertEquals($value, $actual);
    }

    /**
     * @covers Geekwright\Po\PoInitAbstract::msginitFile
     */
    public function testMsginitFile()
    {
        $result = $this->object->msginitFile(__FILE__);
        $this->assertInstanceOf('Geekwright\Po\PoFile', $result);
    }

    /**
     * @covers Geekwright\Po\PoInitAbstract::msginitFile
     */
    public function testMsginitFileException()
    {
        $this->setExpectedException('Geekwright\Po\Exceptions\FileNotReadableException');
        $result = $this->object->msginitFile(__DIR__ . '/notavalidfile');
    }

    /**
     * @covers Geekwright\Po\PoInitAbstract::escapeForPo
     */
    public function testEscapeForPo()
    {
        $actual = $this->object->escapeForPo("'test\r\n'");
        $this->assertEquals('test\n', $actual);
    }
}
